=== szv/BachelorArbeit2_Szvetecz/Schema/device.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://raw.githubusercontent.com/szv/BachelorArbeit2_Szvetecz/main/Schema/device.schema.json",
    "title": "Device",
    "description": "A device, contained by a project.",
    "type": "object",
    "properties": {
        "setupId": {
            "description": "An UUID/GUID which is used to identify the device during registration.",
            "type": "string",
            "pattern": "^[0-9a-fA-F]{8}\\-?[0-9a-fA-F]{4}\\-?[0-9a-fA-F]{4}\\-?[0-9a-fA-F]{4}\\-?[0-9a-fA-F]{12}$"
        },
        "name": {
            "description": "The name of the device.",
            "type": "string",
            "minLength": 5,
            "maxLength": 200
        },
        "description": {
            "description": "The description of the device.",
            "type": "string",
            "maxLength": 1000
        },
        "interval": {
            "type": "number",
            "description": "The time that elapses between the transmissions of the data. (seconds)",
            "minimum": 1,
            "maximum": 99360,
            "default": 3600
        },
        "actors": {
            "type": "array",
            "uniqueItems": true,
            "items": {
                "$ref": "https://raw.githubusercontent.com/szv/BachelorArbeit2_Szvetecz/main/Schema/actor.schema.json"
            }
        },
        "measurements": {
            "type": "array",
            "uniqueItems": true,
            "items": {
                "$ref": "https://raw.githubusercontent.com/szv/BachelorArbeit2_Szvetecz/main/Schema/measurement.schema.json"
            }
        }
    },
    "required": ["setupId", "name", "interval"]
}

=== szv/BachelorArbeit2_Szvetecz/DigitalTwinConfiguration/DeviceAgent/device-configuration.json
{
  "setupId": "9d7f453b-aa83-4d39-ac41-15ef6c7a6a80",
  "name": "device1",
  "description": "A device",
  "interval": 60,
  "actors": [
    {
      "name": "actor1",
      "description": "A actor",
      "type": "switch"
    }
  ],
  "measurements": [
    {
      "name": "measurement1",
      "description": "A measurement",
      "unit": "celcius",
      "interval": 20
    }
  ]
}
