=== szv/BachelorArbeit2_Szvetecz/Schema/project.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://raw.githubusercontent.com/szv/BachelorArbeit2_Szvetecz/main/Schema/project.schema.json",
    "title": "Project",
    "description": "Represents a project.",
    "type": "object",
    "properties": {
        "name": {
            "description": "The name of the project.",
            "type": "string",
            "minLength": 5,
            "maxLength": 200
        },
        "description": {
            "description": "The description of the project.",
            "type": "string",
            "maxLength": 1000
        },
        "company": {
            "description": "The company of the project.",
            "type": "object",
            "$ref": "https://raw.githubusercontent.com/szv/BachelorArbeit2_Szvetecz/main/Schema/company.schema.json"
        },
        "devices": {
            "description": "The devices contained by this project.",
            "type": "array",
            "uniqueItems": true,
            "items": {
                "$ref": "https://raw.githubusercontent.com/szv/BachelorArbeit2_Szvetecz/main/Schema/device.schema.json"
            }
        }
    },
    "required": ["name"]
}

=== szv/BachelorArbeit2_Szvetecz/Schema/test.json
{
    "$schema": "https://raw.githubusercontent.com/szv/BachelorArbeit2_Szvetecz/main/Schema/project.schema.json",
    "name": "project1",
    "description": "Ich bin ein Project",
    "company": {
        "name": "company1",
        "email": "test@fhwn.ac.at"
    },
    "devices": [
        {
            "setupId": "9d7f453b-aa83-4d39-ac41-15ef6c7a6a80",
            "name": "device1",
            "description": "A device",
            "interval": 60,
            "actors": [
                {
                    "name": "actor1",
                    "description": "A actor",
                    "type": "switch"
                }
            ],
            "measurements": [
                {
                    "name": "measurement1",
                    "description": "A measurement",
                    "unit": "celcius",
                    "interval": 20
                }
            ]
        }
    ]
}
